### ISSUE TITLE
The "android" command is deprecated.

### ISSUE THREAD

**Issue by abdulbasetbasher** [codelv/enaml-native#30]
when run :
./enaml-native build-python

```
  STDOUT:
[INFO]:    Will compile for the following archs: x86
[INFO]:    Getting Android API version from user argument
Traceback (most recent call last):
  File "p4a.py", line 4, in <module>
    main()
  File "/home/mrscript/files/Desktop/enaml-native/python-for-android/pythonforandroid/toolchain.py", line 922, in main
    ToolchainCL()
  File "/home/mrscript/files/Desktop/enaml-native/python-for-android/pythonforandroid/toolchain.py", line 528, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/mrscript/files/Desktop/enaml-native/python-for-android/pythonforandroid/toolchain.py", line 142, in wrapper_func
    user_ndk_ver=self.ndk_version)
  File "/home/mrscript/files/Desktop/enaml-native/python-for-android/pythonforandroid/build.py", line 232, in prepare_build_environment
    targets = android('list').stdout.decode('utf-8').split('\n')
  File "/usr/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /home/mrscript/Android/Sdk/tools/android list

  STDOUT:
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "list"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
```

**Comment by frmdstryr** [comment]
Thank you for reporting this! I've merged the fix in from python-for-android. Please see if it's now fixed.

**Comment by frmdstryr** [comment]
@abdulbasetbasher  are you still having this issue?

**Comment by frmdstryr** [comment]
Now confirmed working (along with https://github.com/codelv/enaml-native/commit/d1851e492bd403f1d9987ded8f58e1bad6f1eef7). Please reopen or create a new ticket if there are still issues.
