### ISSUE TITLE
WifiManager.get_connection_info crashes when WiFi not connected

### ISSUE THREAD

**Issue by neil-pozetroninc** [codelv/enaml-native#50]
During testing I found that the call to get_connection_info will crash out with a NullPointerException if the WiFi is not connected when the method is called.

You also can't guard it with a Look Before You Leap call to WifiManager.is_wifi_enabled() as that may return True but the WiFi can still disconnect before the call to get_connection_info.

```
11-23 21:51:34.558 26555 26555 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at org.msgpack.core.MessagePacker.packString(MessagePacker.java:717)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge.lambda$registerBuiltinPackers$21(Bridge.java:322)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge$$Lambda$22.pack(Unknown Source)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge$BridgeGenericPacker.pack(Bridge.java:1540)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge.onEvent(Bridge.java:1161)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge.onResult(Bridge.java:1087)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge.updateObject(Bridge.java:910)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge.lambda$null$29(Bridge.java:1361)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge$$Lambda$32.run(Unknown Source)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge.runUntilCurrent(Bridge.java:1249)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge.lambda$null$37(Bridge.java:1421)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.codelv.enamlnative.Bridge$$Lambda$40.run(Unknown Source)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:152)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5497)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-23 21:51:34.558 26555 26555 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by frmdstryr** [comment]
Thanks for reporting this. It seems that android returns an object with null values when it's not connected instead of a null object. 

It should now return None when no connection is present. Let me know if you still see the issue.

**Comment by neil-pozetroninc** [comment]
Fixed, thanks!
