### ISSUE TITLE
Python 3 AndroidManifest.xml Error: uses-sdk:minSdkVersion 9 in library [:enaml-native]

### ISSUE THREAD

**Issue by mouEsam** [codelv/enaml-native#63]
It only happens when i choose python3.6 but runs fine with python2.7
`
> Task :app:processDebugManifest
/media/m-essam/MyData/Workspace/HelloWorld/android/app/src/main/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 9 cannot be smaller than version 21 declared in library [:enaml-native] /media/m-essam/MyData/Workspace/HelloWorld/venv/android/enaml-native/build/intermediates/manifests/full/debug/AndroidManifest.xml as the library might be using APIs not available in 9
        Suggestion: use a compatible library with a minSdk of at most 9,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.codelv.enamlnative" to force usage (may lead to runtime failures)

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 9 cannot be smaller than version 21 declared in library [:enaml-native] /media/m-essam/MyData/Workspace/HelloWorld/venv/android/enaml-native/build/intermediates/manifests/full/debug/AndroidManifest.xml as the library might be using APIs not available in 9
        Suggestion: use a compatible library with a minSdk of at most 9,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.codelv.enamlnative" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
17 actionable tasks: 2 executed, 15 up-to-date

Exception in thread background thread for pid 4445:
Traceback (most recent call last):
  File "/home/m-essam/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/m-essam/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/m-essam/.local/lib/python3.6/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/m-essam/.local/lib/python3.6/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/m-essam/.local/lib/python3.6/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: ./gradlew installDebug

  STDOUT:
<-------------> 1% E... (72364 more, please see e.stdout)
> :enaml-native:bundlePython
  STDERR:
[DEBUG]:   -> running  cd /media/m-essam/MyData/Workspace/HelloWorld
Traceback (most recent call last):
  File "/home/m-essam/anaconda3/bin/enaml-native", line 10, in <module>
    sys.exit(main())
  File "/home/m-essam/anaconda3/lib/python3.6/site-packages/enamlnativecli/main.py", line 1657, in main
    EnamlNativeCli().start()
  File "/home/m-essam/anaconda3/lib/python3.6/site-packages/enamlnativecli/main.py", line 1651, in start
    cmd.run(self.args)
  File "/home/m-essam/anaconda3/lib/python3.6/site-packages/enamlnativecli/main.py", line 1199, in run
    shprint(gradlew, 'installDebug',*args.extra, _debug=True)
  File "/home/m-essam/anaconda3/lib/python3.6/site-packages/enamlnativecli/main.py", line 89, in shprint
    for c in cmd(*args, **kwargs):
  File "/home/m-essam/.local/lib/python3.6/site-packages/sh.py", line 720, in next
    self.wait()
  File "/home/m-essam/.local/lib/python3.6/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/m-essam/.local/lib/python3.6/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: ./gradlew installDebug

  STDOUT:
<-------------> 1% E... (72364 more, please see e.stdout)
> :enaml-native:bundlePython
  STDERR:

`
should i just choose 2.7 but program in 3.6 in main.py? or is it impossible?

**Comment by frmdstryr** [comment]
enaml-native currently requires apps to use a minSdkVersion version of 21 which supports about ~87% of devices (see https://developer.android.com/about/dashboards/#Platform). 

I suggest that you modify the `minSdkVersion` in `android/app/build.gradle` to use 21 or higher or create a new app and leave the min sdk option at the default.

Thank you.

**Comment by mouEsam** [comment]
I'll check it out when I get my hands on my PC tonight 
Thank you for your time

**Comment by mouEsam** [comment]
Yup you where right somehow the build.gradle had it pointing to 9
Don't know how it happened
Thank you
