### ISSUE TITLE
Python 3.6 not selected in Android.md

### ISSUE THREAD

**Issue by mouEsam** [codelv/enaml-native#64]
When I first created the application and ran it it complained about pythons2.7.so missing although I chose python3.6 so I editted android.md PY_VER to 3.6m .. it ran

I think the cli need to edit it automatically when selecting 3.6

**Comment by frmdstryr** [comment]
The cli will update Android.mk to use the version of python installed. So if you're using python 3.6 for the app, I recommend using miniconda3.

**Comment by rodgomesc** [comment]
For me is working fine, with python3 and miniconda3

Em dom, 13 de mai de 2018 17:12, frmdstryr <notifications@github.com>
escreveu:

**Comment by mouEsam** [comment]
I have anaconda3 
Also after pushing the APK to my phone it complained about a missing lib



java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.helloworld-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.helloworld-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libpybridge.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:972)
	at java.lang.System.loadLibrary(System.java:1530)
	at com.codelv.enamlnative.python.PythonInterpreter.<clinit>(PythonInterpreter.java:100)
	at com.codelv.enamlnative.python.PythonInterpreter.instance(PythonInterpreter.java:23)
	at com.codelv.enamlnative.Bridge.<init>(Bridge.java:139)
	at com.codelv.enamlnative.packages.BridgePackage.onCreate(BridgePackage.java:18)
	at com.codelv.enamlnative.EnamlActivity.onCreate(EnamlActivity.java:67)
	at android.app.Activity.performCreate(Activity.java:6847)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6342)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by rodgomesc** [comment]
What `which python` returns?

**Comment by mouEsam** [comment]
When venv is activated it returns 
/////venv/bin/python
Otherwise it returns
~/anaconda3/bin/python

**Comment by rodgomesc** [comment]
With the venv **deactivated**, what `pip list | grep enaml` returns

**Comment by mouEsam** [comment]
I created another project with python3.6 ran it and pushed it to my phone and no complaints at all
Except for the Android.mk thingy which I had to do again to make it point to the right version of libpython
So is it that my version of enaml-native-cli is a little old or there really is something wrong with the CLI
I just installed it yesterday 
And thank you so much for bearing with me 🙂

**Comment by rodgomesc** [comment]
everything is working fine here with `enaml-native-cli==2.2.6`

**Comment by mouEsam** [comment]
seems that my installation of anaconda3 only finds 2.2.4 of enaml-native-cli so I edited main.py of my enaml-native-cli to do the trick
thank you for your time

**Comment by rodgomesc** [comment]
This is not the correct way to do this, between version 2.2.4 and 2.2.6, Several files have been changed, uninstall it and install again from github

**Comment by mouEsam** [comment]
Well then I'll do that ..
Thank you again 😃
