### ISSUE TITLE
Execution failed for task ':enaml-native:bundlePython'

### ISSUE THREAD

**Issue by Cleiton-D** [codelv/enaml-native#79]
when trying to make the app for android i am getting this error:
`> Task :enaml-native:bundlePython FAILED
[DEBUG]:   -> running cd /home/cleiton/miniconda3/android/enaml-native/src/main/jni
Traceback (most recent call last):
  File "/home/cleiton/miniconda3/bin/enaml-native", line 10, in <module>
    sys.exit(main())
  File "/home/cleiton/miniconda3/lib/python3.7/site-packages/enamlnativecli/main.py", line 1657, in main
    EnamlNativeCli().start()
  File "/home/cleiton/miniconda3/lib/python3.7/site-packages/enamlnativecli/main.py", line 1651, in start
    cmd.run(self.args)
  File "/home/cleiton/miniconda3/lib/python3.7/site-packages/enamlnativecli/main.py", line 474, in run
    self.cmds['ndk-build'].run(args)
  File "/home/cleiton/miniconda3/lib/python3.7/site-packages/enamlnativecli/main.py", line 386, in run
    with cd(jni_dir):
  File "/home/cleiton/miniconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/cleiton/miniconda3/lib/python3.7/site-packages/enamlnativecli/main.py", line 55, in cd
    os.chdir(os.path.expanduser(newdir))
FileNotFoundError: [Errno 2] No such file or directory: '/home/cleiton/miniconda3/android/enaml-native/src/main/jni'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':enaml-native:bundlePython'.
> Process 'command 'enaml-native'' finished with non-zero exit value 1`

**Comment by frmdstryr** [comment]
I just updated the python builds and released a more up to day build of enaml-native and enaml-native-cli. 

Please update the cli (using `pip install --upgrade enaml-native-cli`) and please try to create an app again.

Sorry for the delayed response!

**Comment by aprilahijriyan** [comment]
same problem

**Comment by aprilahijriyan** [comment]
in my case, I experienced something like this.
```
[DEBUG] Building for 3.7m
Traceback (most recent call last):
  File "venv/bin/enaml-native", line 8, in <module>
    sys.exit(main())
  File "/home/april/miniconda3/envs/helloworld/lib/python3.7/site-packages/enamlnativecli/main.py", line 1772, in main
    EnamlNativeCli().start()
  File "/home/april/miniconda3/envs/helloworld/lib/python3.7/site-packages/enamlnativecli/main.py", line 1766, in start
    cmd.run(self.args)
  File "/home/april/miniconda3/envs/helloworld/lib/python3.7/site-packages/enamlnativecli/main.py", line 582, in run
    self.cmds['ndk-build'].run(args)
  File "/home/april/miniconda3/envs/helloworld/lib/python3.7/site-packages/enamlnativecli/main.py", line 461, in run
    'ndk-build.cmd' if IS_WIN else 'ndk-build'
  File "/home/april/miniconda3/envs/helloworld/lib/python3.7/site-packages/sh.py", line 1202, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: /home/april/Android/Sdk//ndk-bundle/ndk-build

```
maybe this happened because of a merging path `/home/april/Android/Sdk//ndk-bundle/ndk-build` ?
