### ISSUE TITLE
Error: "Could not create a link to the env!"

### ISSUE THREAD

**Issue by null0nil** [codelv/enaml-native#82]
enaml-native-cli version 2.3.1    

I ran "enaml-native create app" and got the follow error:
```
#
# To activate this environment, use
#
#     $ conda activate helloworld
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Could not create a link to the env!
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Traceback (most recent call last):
  File "/share/Projects/android/enaml/venv3/bin/enaml-native", line 8, in <module>
    sys.exit(main())
  File "/share/Projects/android/enaml/venv3/lib/python3.6/site-packages/enamlnativecli/main.py", line 1772, in main
    EnamlNativeCli().start()
  File "/share/Projects/android/enaml/venv3/lib/python3.6/site-packages/enamlnativecli/main.py", line 1766, in start
    cmd.run(self.args)
  File "/share/Projects/android/enaml/venv3/lib/python3.6/site-packages/enamlnativecli/main.py", line 259, in run
    overwrite_if_exists=args.overwrite_if_exists)
  File "/share/Projects/android/enaml/venv3/lib/python3.6/site-packages/cookiecutter/main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "/share/Projects/android/enaml/venv3/lib/python3.6/site-packages/cookiecutter/generate.py", line 376, in generate_files
    delete_project_on_failure
  File "/share/Projects/android/enaml/venv3/lib/python3.6/site-packages/cookiecutter/generate.py", line 236, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/share/Projects/android/enaml/venv3/lib/python3.6/site-packages/cookiecutter/hooks.py", line 144, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/share/Projects/android/enaml/venv3/lib/python3.6/site-packages/cookiecutter/hooks.py", line 128, in run_script_with_context
    run_script(temp.name, cwd)
  File "/share/Projects/android/enaml/venv3/lib/python3.6/site-packages/cookiecutter/hooks.py", line 91, in run_script
    'Hook script failed (exit status: {})'.format(exit_status)
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 1)
(venv3) 
```

**Comment by null0nil** [comment]
Moved to https://github.com/codelv/enaml-native-cli/issues/20
